services:
  backend:
    stdin_open: true
    tty: true
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    volumes:
      - ./app:/code/app
    ports:
      - "8080:8080"
    env_file:
      - .env
  redis:
    image: "redis:7.2.4-alpine"
    ports:
      - "6379:6379"
    depends_on:
      - backend
  celery:
    build: .
    command: celery -A app.tasks worker -l info
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    depends_on:
      - backend
      - redis
